#! /bin/bash
EWW="eww -c $HOME/.config/eww/topbar"
if [[ "$1" = "-i" ]]; then
	pamixer -i "$2"
elif [[ "$1" = "-d" ]]; then
	pamixer -d "$2"
elif [[ "$1" = "-t" ]]; then
	pamixer -t
elif [[ "$1" = "-s" ]]; then
	pamixer --set-volume "$2"
fi
${EWW} update speaker_volume="$(bash ~/.local/share/scripts/system/get-speaker-info --volume)"
${EWW} update speaker_icon="$(bash ~/.local/share/scripts/system/get-speaker-info --icon)"
${EWW} update speaker_status="$(bash ~/.local/share/scripts/system/get-speaker-info --status)"
